[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "meu_pacote"
description = "Código do projeto Saudação"
version = "0.1.0"
readme = "README.md"
dependencies = ["colorama"]